import sys
import json
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import JSONFormatter

def main():
    if len(sys.argv) < 2:
        print(json.dumps({"error": "No video ID provided"}))
        sys.exit(1)

    video_id = sys.argv[1]

    try:
        ytt_api = YouTubeTranscriptApi()
        transcript_list = ytt_api.list(video_id)

        result = {
            "languages": [],
            "subtitles": {}
        }

        for transcript in transcript_list:
            lang_info = {
                "languageCode": transcript.language_code,
                "name": transcript.language,
                "isAutoGenerated": transcript.is_generated,
            }
            result["languages"].append(lang_info)

            try:
                segments = transcript.fetch()
                result["subtitles"][transcript.language_code] = {
                    "segments": [
                        {
                            "text": seg.text,
                            "start": seg.start,
                            "duration": seg.duration,
                        }
                        for seg in segments
                    ],
                    "error": None
                }
            except Exception as e:
                result["subtitles"][transcript.language_code] = {
                    "segments": [],
                    "error": str(e)
                }

        print(json.dumps(result, ensure_ascii=False))

    except Exception as e:
        print(json.dumps({"error": str(e)}, ensure_ascii=False))
        sys.exit(1)

if __name__ == "__main__":
    main()
