import express from 'express';
import { Innertube } from 'youtubei.js';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const app = express();
const PORT = 3000;

let innertube = null;

async function getInnertube() {
  if (!innertube) {
    innertube = await Innertube.create();
  }
  return innertube;
}

function extractVideoId(input) {
  if (!input) return null;
  input = input.trim();

  if (/^[a-zA-Z0-9_-]{11}$/.test(input)) return input;

  try {
    const url = new URL(input);
    if (url.hostname.includes('youtube.com') && url.searchParams.has('v')) return url.searchParams.get('v');
    if (url.hostname === 'youtu.be') return url.pathname.slice(1).split('/')[0];
    const m = url.pathname.match(/\/(embed|v|shorts)\/([a-zA-Z0-9_-]{11})/);
    if (m) return m[2];
  } catch { /* not a URL */ }

  return null;
}

function formatTime(seconds) {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const ms = Math.round((seconds % 1) * 1000);
  const msStr = String(ms).padStart(3, '0');
  if (h > 0) return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${msStr}`;
  return `${m}:${String(s).padStart(2, '0')}.${msStr}`;
}

function extractSegments(transcriptInfo) {
  const segments = [];
  const body = transcriptInfo.transcript?.content?.body;
  if (!body?.initial_segments) return segments;

  for (const seg of body.initial_segments) {
    if (seg.type !== 'TranscriptSegment') continue;

    const startMs = parseInt(seg.start_ms, 10) || 0;
    const endMs = parseInt(seg.end_ms, 10) || 0;
    const durationMs = endMs - startMs;
    const text = seg.snippet?.toString?.() || '';

    if (!text.trim()) continue;

    segments.push({
      text: text.trim(),
      start: startMs / 1000,
      duration: durationMs / 1000,
      startFormatted: seg.start_time_text?.toString?.() || formatTime(startMs / 1000),
      endFormatted: formatTime(endMs / 1000),
    });
  }

  return segments;
}

app.use(express.static(join(__dirname, 'public')));

// ─── Get available languages only (fast, no subtitle fetching) ───
app.get('/api/languages', async (req, res) => {
  try {
    const videoId = extractVideoId(req.query.videoId);
    if (!videoId) return res.status(400).json({ error: 'URL o ID de video inválido' });

    const method = req.query.method || 'youtubei';
    console.log(`\n► [languages/${method}] ${videoId}`);

    if (method === 'supadata') {
      const result = await supadataFetchLangs(videoId);
      return res.json(result);
    }

    // youtubei.js path
    const yt = await getInnertube();
    const info = await yt.getInfo(videoId);

    let title = info.basic_info?.title || '';
    let author = info.basic_info?.author || '';
    const duration = info.basic_info?.duration || 0;

    // Fallback: oEmbed for title/author when InnerTube returns empty (cloud IP blocking)
    if (!title || !author) {
      try {
        const oembed = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`).then(r => r.ok ? r.json() : {}).catch(() => ({}));
        title = title || oembed.title || 'Sin título';
        author = author || oembed.author_name || 'Desconocido';
      } catch { /* ignore */ }
    }

    let transcriptInfo;
    try {
      transcriptInfo = await info.getTranscript();
    } catch (firstErr) {
      try { transcriptInfo = await info.getTranscript(); } catch { /* no transcripts */ }
    }

    // caption_tracks: all available tracks including ASR (auto-generated)
    const captionTracks = info.captions?.caption_tracks || [];
    const rawLangs = transcriptInfo?.languages || [];
    const selectedLang = transcriptInfo?.selectedLanguage || '';

    console.log(`  caption_tracks: [${captionTracks.map(t => `${t.language_code}/${t.kind || 'manual'} "${t.name}"`).join(', ')}]`);
    console.log(`  transcript langs: [${rawLangs.join(', ')}] | selected: "${selectedLang}"`);

    const isAutoStr = s => typeof s === 'string' && (
      s.includes('auto-generated') || s.includes('generado') || s.includes('automático')
    );

    const seen = new Set();
    const languages = [];

    // 1. Primary: transcript panel language names (these work with selectLanguage())
    rawLangs.forEach(lang => {
      if (!seen.has(lang)) {
        seen.add(lang);
        languages.push({ languageCode: lang, name: lang, isAutoGenerated: isAutoStr(lang) });
      }
    });

    // 2. Fallback: selected language if not already listed
    if (selectedLang && !seen.has(selectedLang)) {
      seen.add(selectedLang);
      languages.push({ languageCode: selectedLang, name: selectedLang, isAutoGenerated: isAutoStr(selectedLang) });
    }

    // 3. Supplement: caption_tracks that aren't represented yet (especially ASR tracks)
    captionTracks.forEach(track => {
      const isAsr = track.kind === 'asr';
      const trackName = track.name?.toString?.() || track.language_code;
      const baseName = trackName.replace(/\s*\(.*\)/, '').trim().toLowerCase();

      // Check if this track type is already listed
      const alreadyListed = languages.some(l => {
        const lBase = l.name.replace(/\s*\(.*\)/, '').trim().toLowerCase();
        return lBase === baseName && l.isAutoGenerated === isAsr;
      });

      if (!alreadyListed) {
        const displayName = isAsr ? `${trackName} (auto-generated)` : trackName;
        if (!seen.has(displayName)) {
          seen.add(displayName);
          languages.push({ languageCode: displayName, name: displayName, isAutoGenerated: isAsr });
        }
      }
    });

    if (languages.length === 0) {
      // If caption_tracks is also empty, YouTube likely blocked this server's IP
      const blockedByYT = captionTracks.length === 0 && !transcriptInfo;
      const warning = blockedByYT
        ? 'youtubei.js no puede acceder a YouTube desde este servidor (IP de servidor cloud bloqueada). Usa el método Supadata.'
        : 'Este video no tiene subtítulos disponibles';
      return res.json({ videoId, title, author, duration, languages: [], warning });
    }

    res.json({ videoId, title, author, duration, languages });
  } catch (err) {
    console.error('[languages] Error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/subtitles', async (req, res) => {
  try {
    const videoId = extractVideoId(req.query.videoId);
    if (!videoId) {
      return res.status(400).json({ error: 'URL o ID de video inválido' });
    }

    console.log(`\n► Processing: ${videoId}`);
    const yt = await getInnertube();
    const info = await yt.getInfo(videoId);

    const videoData = {
      id: videoId,
      title: info.basic_info?.title || 'Sin título',
      author: info.basic_info?.author || 'Desconocido',
      duration: info.basic_info?.duration || 0,
      thumbnail: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
      captionTracks: [],
      subtitles: {},
    };

    // Get transcript via engagement panel (POST /get_transcript, not timedtext GET)
    let transcriptInfo;
    try {
      transcriptInfo = await info.getTranscript();
    } catch (firstErr) {
      console.log(`  Retry getTranscript after error: ${firstErr.message}`);
      try {
        transcriptInfo = await info.getTranscript();
      } catch (err) {
        console.log(`  No transcript panel: ${err.message}`);
        return res.json({ ...videoData, warning: 'Este video no tiene subtítulos disponibles' });
      }
    }

    const availableLanguages = transcriptInfo.languages || [];
    const selectedLanguage = transcriptInfo.selectedLanguage || '';

    console.log(`  Languages: [${availableLanguages.join(', ')}]`);
    console.log(`  Default: "${selectedLanguage}"`);

    // Build caption tracks from available languages
    videoData.captionTracks = availableLanguages.map(lang => ({
      languageCode: lang,
      name: lang,
      kind: lang.includes('auto-generated') || lang.includes('generado') ? 'asr' : 'manual',
      isAutoGenerated: lang.includes('auto-generated') || lang.includes('generado'),
    }));

    // If a specific language is requested, fetch only that one
    const requestedLang = req.query.lang;
    const langsToFetch = requestedLang
      ? availableLanguages.filter(l => l === requestedLang)
      : availableLanguages;

    // Fetch default language segments
    if (!requestedLang || requestedLang === selectedLanguage) {
      const defaultSegments = extractSegments(transcriptInfo);
      videoData.subtitles[selectedLanguage] = { segments: defaultSegments, error: null };
      console.log(`  ✓ "${selectedLanguage}": ${defaultSegments.length} segments`);
    }

    // Fetch additional languages
    for (const lang of langsToFetch) {
      if (lang === selectedLanguage) continue;
      console.log(`  Fetching "${lang}"...`);
      try {
        let langTranscript;
        try {
          langTranscript = await transcriptInfo.selectLanguage(lang);
        } catch (firstErr) {
          // Try fuzzy match against available transcript panel languages
          const isAsr = lang.includes('auto-generated') || lang.includes('generado');
          const base = lang.replace(/\s*\(.*\)/, '').trim().toLowerCase();
          const match = availableLanguages.find(l => {
            const lBase = l.replace(/\s*\(.*\)/, '').trim().toLowerCase();
            const lIsAsr = l.includes('auto-generated') || l.includes('generado');
            return lBase === base && lIsAsr === isAsr;
          });
          if (match && match !== lang) {
            console.log(`  Fuzzy match "${lang}" → "${match}"`);
            langTranscript = await transcriptInfo.selectLanguage(match);
          } else {
            console.log(`  Retry "${lang}" after error: ${firstErr.message}`);
            langTranscript = await transcriptInfo.selectLanguage(lang);
          }
        }
        const segments = extractSegments(langTranscript);
        videoData.subtitles[lang] = { segments, error: null };
        console.log(`  ✓ "${lang}": ${segments.length} segments`);
      } catch (err) {
        console.error(`  ✗ "${lang}": ${err.message}`);
        videoData.subtitles[lang] = { segments: [], error: err.message };
      }
    }

    console.log(`  Done.`);
    res.json(videoData);
  } catch (err) {
    console.error('Error:', err.message);
    if (err.message?.includes('unavailable') || err.message?.includes('private')) {
      return res.status(404).json({ error: 'Video no disponible o es privado' });
    }
    res.status(500).json({ error: 'Error al procesar el video: ' + err.message });
  }
});

// ─── Supadata.ai endpoint ───

const SUPADATA_API_KEY = 'sd_a7a62696feefc34d0b612cd4edb446f3';

async function supadataFetchLangs(videoId) {
  const result = await supadataFetch(videoId, SUPADATA_API_KEY);
  const defaultLang = result.lang || 'en';
  const availableLangs = result.availableLangs || [defaultLang];
  const oembed = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`).then(r => r.ok ? r.json() : {}).catch(() => ({}));
  return {
    videoId,
    title: oembed.title || '',
    author: oembed.author_name || '',
    duration: 0,
    languages: availableLangs.map(lang => ({
      languageCode: lang,
      name: lang.toUpperCase(),
      isAutoGenerated: false,
    })),
  };
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function supadataFetch(videoId, apiKey, lang = null) {
  const ytUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const params = new URLSearchParams({ url: ytUrl, text: 'false' });
  if (lang) params.set('lang', lang);

  const response = await fetch(`https://api.supadata.ai/v1/transcript?${params}`, {
    headers: { 'x-api-key': apiKey },
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`Supadata ${response.status}: ${body}`);
  }

  const data = await response.json();

  // Handle async jobs
  if (data.jobId) {
    return await pollSupadataJob(data.jobId, apiKey);
  }

  return data;
}

async function pollSupadataJob(jobId, apiKey, maxAttempts = 30) {
  for (let i = 0; i < maxAttempts; i++) {
    await sleep(1000);
    const response = await fetch(`https://api.supadata.ai/v1/transcript/${jobId}`, {
      headers: { 'x-api-key': apiKey },
    });
    if (!response.ok) continue;
    const data = await response.json();
    if (data.status === 'completed') return data;
    if (data.status === 'failed') throw new Error(data.error || 'Job failed');
  }
  throw new Error('Supadata job timed out');
}

function supadataToSegments(content) {
  if (!Array.isArray(content)) return [];
  return content
    .filter(c => c.text?.trim())
    .map(c => {
      const startSec = (c.offset || 0) / 1000;
      const durSec = (c.duration || 0) / 1000;
      return {
        text: c.text.trim(),
        start: startSec,
        duration: durSec,
        startFormatted: formatTime(startSec),
        endFormatted: formatTime(startSec + durSec),
      };
    });
}

app.get('/api/subtitles-supadata', async (req, res) => {
  try {
    const videoId = extractVideoId(req.query.videoId);
    if (!videoId) {
      return res.status(400).json({ error: 'URL o ID de video inválido' });
    }

    const requestedLang = req.query.lang || null;
    const apiKey = SUPADATA_API_KEY;

    console.log(`\n► [Supadata] Processing: ${videoId} lang=${requestedLang || 'all'}`);

    // First call: get default language + available languages
    const defaultResult = await supadataFetch(videoId, apiKey);
    const defaultLang = defaultResult.lang || 'en';
    const availableLangs = defaultResult.availableLangs || [defaultLang];

    console.log(`  Default lang: ${defaultLang}`);
    console.log(`  Available: [${availableLangs.join(', ')}]`);

    const videoData = {
      id: videoId,
      title: '',
      author: '',
      duration: 0,
      thumbnail: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
      captionTracks: availableLangs.map(lang => ({
        languageCode: lang,
        name: lang.toUpperCase(),
        kind: 'manual',
        isAutoGenerated: false,
      })),
      subtitles: {},
    };

    // Determine which languages to fetch
    const langsToFetch = requestedLang ? [requestedLang] : availableLangs;

    // Parse default language segments if needed
    if (langsToFetch.includes(defaultLang)) {
      const defaultSegments = supadataToSegments(defaultResult.content);
      videoData.subtitles[defaultLang] = { segments: defaultSegments, error: null };
      console.log(`  ✓ ${defaultLang}: ${defaultSegments.length} segments`);
    }

    // Fetch remaining languages
    for (const lang of langsToFetch) {
      if (lang === defaultLang) continue;
      console.log(`  Fetching ${lang}...`);
      try {
        const langResult = await supadataFetch(videoId, apiKey, lang);
        const segments = supadataToSegments(langResult.content);
        videoData.subtitles[lang] = { segments, error: null };
        console.log(`  ✓ ${lang}: ${segments.length} segments`);
      } catch (err) {
        console.error(`  ✗ ${lang}: ${err.message}`);
        videoData.subtitles[lang] = { segments: [], error: err.message };
      }
    }

    // Try to get video metadata
    try {
      const metaRes = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`);
      if (metaRes.ok) {
        const meta = await metaRes.json();
        videoData.title = meta.title || '';
        videoData.author = meta.author_name || '';
      }
    } catch { /* ignore meta errors */ }

    console.log(`  Done.`);
    res.json(videoData);
  } catch (err) {
    console.error('[Supadata] Error:', err.message);
    res.status(500).json({ error: 'Error Supadata: ' + err.message });
  }
});

app.listen(PORT, () => {
  console.log(`Servidor corriendo en http://localhost:${PORT}`);
});
